run:
  timeout: 5m
  skip-dirs:
    - .github
    - hack
    - vendor
linters:
  disable-all: true
  enable:
    - gofmt
    - revive
    - goimports
    - govet
    - unused
    - whitespace
    - misspell
  fast: false
linters-settings:
  gofmt:
    simplify: false
issues:
  exclude-use-default: false
